endlessm/gdm

- data/gdm.service.in
This helps with flicker when the X server shuts down.
[endlessm/eos-shell#2227]
> systemd: clear terminal after starting and before stopping

- daemon/gdm-session-worker.c
When asking for a new password in PAM<->Shell conversation, at the end
ask also for the password hint and save within user details.
[endlessm/eos-shell#1623]
> worker: setup password hint

- debian/control
It has been renamed to adwaita-icon-theme.
[endlessm/eos-shell#4538]
> Don't depend on gnome-icon-theme anymore

- configure.ac
- data/Makefile.am
Most distros use custom logic for their Xsession, so we can't really
ship a default here. Doing so would break people running "make install"
and expecting things to work.
https://bugzilla.gnome.org/show_bug.cgi?id=750220
[endlessm/eos-shell#5116]
> Make Xsession installation conditional, and off by default

- configure.ac
Cherry-pick build fix from upstream.
[endlessm/eos-shell#4921]
> build: transition to libsystemd

- configure.ac
No change is simple enough not to be tested :-(
[endlessm/eos-shell#4921]
> Fix syntax error introduced in last commit

- daemon/gdm-session-worker.c
For some reason this gets the right PAM modules (gkr-pam, pam_unix)
working for the use case of a passwordless user loging in for the 1st
time, so that the right auth error gets reported allowing to effectively
set the password for the 1st time from GDM.
This is probably not a real fix, but a workaround (and a partial revert
of 4cc94727) while we don't find the true reason why this is working
this way, so that users don't get a broken experience in the meanwhile.
[endlessm/eos-shell#5370]
> session-worker: set the display name as a TTY pam item on initialization

- daemon/gdm-simple-slave.c
- data/gdm.service.in
We are seeing terminal messages on logout and shutdown. The first message
visible is: Started GNOME display manager
It is easy to see why this is happening - systemd prints this message
(and others) after gdm.service has fully started, which is even after
ExecStartPost.
On logout, there is no change to gdm.service state so nothing clears this.
On shutdown, it appears that ExecStopPost is too late to clear the
messages. For them to be truly hidden, the tty needs to be cleared before
the session is stopped.
I'm not exactly sure how this worked before, but this should be a more
reliable approach. We now clear the messages from inside the gdm process,
once a session has started successfully.
[endlessm/eos-shell#5458]
> Clear terminal after session has launched

- daemon/gdm-session-worker.c
Made the hint page keep asking for a hint even when set to empty. We now also allow setting a password hint consisting of spaces (see issue comments) to avoid users getting frustrated with this feature.
[endlessm/eos-shell#5906]
> Shell: Fixed handling of empty password hints

- daemon/gdm-session-worker.c
gdm sends this message immediately after PAM sends an equivalent message,
resulting in the message being flashed too quickly for the user to read.
[endlessm/eos-shell#5894]
> session-worker: Don't override PAM's password expired prompt

- data/gdm.service.in
Debian's gdm3 package removes the BusName entry in gdm's unit file,
which is evidently causing gdm to get killed during upgrades. This
changes the unit from type "dbus" to type "simple". The documented
effect of this change is that systemd will start services that
depend on gdm immediately, instead of waiting for gdm to take its
bus name. Frankly, the effects of this could be unpredictable, but
it is what Debian does, so it's probably fine....
[endlessm/eos-shell#5494]
> Attempt to avoid X session being terminated during gdm upgrades

- data/gdm.service.in
Handle restarts more like Debian, and less like gdm upstream. Might
work.
[endlessm/eos-shell#5494]
> Try harder to not die during upgrades

- daemon/gdm-session-worker.c
This comment led me on a bit of a wild goose chase, thinking that it is
possible for an ActUser to never load. Nowadays it will always load,
even if the username does not exist, and no further changes are required
in gdm. See fdo#66325.
https://bugzilla.gnome.org/show_bug.cgi?id=760401
[endlessm/eos-shell#5472]
> session-worker: Remove obsolete FIXME

- daemon/gdm-launch-environment.c
- daemon/gdm-simple-slave.c
The locked down dconf profile should not be used for the initial setup
session. This allows overridden values from the user profile to take
effect.
I couldn't find a good way to determine if we're running initial setup
from inside gdm-launch-environment, similarly I can't see an easy way
to modify the session from gdm-simple-slave, so lets just check the
username.
https://phabricator.endlessm.com/T14574
> launch-environment: Don't set DCONF_PROFILE for gnome-initial-setup

- debian/gdm3.install
There are no files installed in /usr/share/dconf at the moment due
to commit e1b4c1ec, so remove it not to fail building the package.
https://phabricator.endlessm.com/T16450
> Don't install anything from /usr/share/dconf

- data/dconf/defaults/locks/00-upstream-settings-locks
- data/dconf/gdm.in
In the previous PR I overlooked the fact that now upstream defaults are no longer being used to update the binary database for the gdm profile as it used to, but instead a file-db is generated in-tree with dconf compile, which is supposed to be installed under /usr/share/gdm/greeter-dconf-defaults.
Thus, we can't simply replace the `file-db:@DATADIR@/@PACKAGE@/greeter-dconf-defaults` line with a `system-db:gdm` line and call it a day, since that means all the upstream defaults + locks will be ignored. Instead, what we have to do is to restore the `file-db` line and simply add the `system-db:gdm` line before it, so that the GDM db is considered first, then fall back to the upstream defaults.
Last, also backport a patch proposed upstream not to lock a setting that has not been previously …
> Don't ignore the default dconf settings set by upstream 

- debian/gdm3.install
- debian/gdm3.postinst
- debian/gdm3.postrm
Install the upstream default dconf settings, generated with `dconf compile`, in /usr/share/gdm/greeter-dconf-defaults, and include the result file in the gdm3 package, instead of the Debian-specific files that only the -now dropped- `generate-config` script would understand.
Also, in the previous PR I forgot to include the calls to `dconf update` that we need in Endless since we are not using the Debian-specific `generate-config` dynamic mechanism, so add that now too.
https://phabricator.endlessm.com/T16493
> Properly install and handle upstream default dconf settings 

- debian/gdm3.postinst
Default upstream settings are no longer shipped as plain text files
that get compiled with dconf update. Instead, they used to compile
a dconf database at the time of building GDM, which will get installed
in /usr/share/gdm/greeter-dconf-defaults and referenced from the gdm
profile.
Thus, we need to make sure these files from previous versions of GDM get
removed on dist-upgraded systems before running dconf update below (which
we still want to allow extending the defaults with our own things), so that
old values and/or no longer used keys (e.g. session-name) don't get added
into the gdm profile's database.
This fixes an issue when dist-upgraded from eos-shell to gnome-shell 3.22,
as the old upstream-settings from GDM 3.14 file defined 'gdm-shell' as the
session name, making gnome-session …
> Remove plain text files with upstream's default settings on post inst

- debian/gdm3.postinst
- debian/gdm3.postrm
This call to dconf update is an Endless-specific thing, but we don't
want to have the package installation failing in case this call fails
for any reason (e.g. non-existent /etc/dconf/db directory), so make
it more robust against that.
https://phabricator.endlessm.com/T16823
> Don't fail installing/removing a package if dconf update fails

- debian/gdm3.dirs
We previously shipped the gdm greeter session defaults in this folder, but it was later moved to a pre-compiled file in /usr. However, for backwards compatibility reasons in case the user/admin has customised their gdm.d folder with other settings, we still have system-db:gdm in the dconf profile for gdm. We call dconf update in the postinst script to create the /etc/dconf/db/gdm database but because gdm.d doesn't exist, the file is not created, causing a runtime error in dconf. The easiest fix that respects the possibility of user customisation is to create the dir (expecting it to be empty almost always) to create an empty GVariant db to keep dconf happy.
https://phabricator.endlessm.com/T19191
> T19191: create empty /etc/dconf/db/gdm.d

- daemon/gdm-display.c
This reverts commit f0cf45d16fc5fcf3e17aec1e31d00c861b6e0a8f.
After upstream changes to the terminfo definitions on ncurses-base,
virtualbox VMs would boot to a black screen intead of the login manager.
Tracking down those changes, it boiled down to the definition of
capability E3 for linux3.0 terminals, which is now the default
definition for linux terminals. It seems the use of that capability on
framebuffer devices leads to clearing everything on the screen,
including the GDM user selector.
We'll revert manually clearing the terminal from GDM and work on a
better solution for the original problem (seeing terminal messages on
logout and shutdown, https://phabricator.endlessm.com/T5458).
https://phabricator.endlessm.com/T19555
> Revert "Clear terminal after session has launched"

- daemon/gdm-display.c
Clear the screen here to prevent systemd messages from flashing when
logging out / restarting / shutting down, right before handing control
over to plymouth.
Note that we use `tput reset` instead of `clear` (or `tput clear`, which
woudl be equivalent) to make sure that we not only clear the text that
might be visible in the virtual terminal (tty1), but also any other
text that could be accessible by scrolling back. We could have used
`reset`, but that command is too heavy for what we want here (clearing
the console), which is something that `tput reset` does perfectly.
https://phabricator.endlessm.com/T18074
> daemon: clear the console's output when disconnecting from the display

- data/dconf/gdm.in
Currently our image builder dconf overrides are not applied to the gdm
session. Make sure we include them there too, as some are required by
the initial-setup process too, which runs in the gdm session.
https://phabricator.endlessm.com/T24303
> dconf: add image overrides location

- daemon/gdm-display.c
This reverts commit 20c4d5261618cd2d00c5217ed656e12714ecfbde.
Now that the systemd-plymouth integration is fixed systemd does not
print to the console except when plymouth is running, in which case
console redirection is also enabled so all of systemd's output is
printed to a file insted of the actual console.
The only other thing that could print to the console is the kernel,
however, after the work on T24262 it should not print anything to the
console unless the previous boot failed, in which case we don't care
about having a clean shutdown since the boot was already full of
messages.
https://phabricator.endlessm.com/T25396
> Revert "daemon: clear the console's output when disconnecting from the display"

- debian/rules
With the update to gdm-3.32, we turned on user display server
functionality.
However, this breaks nvidia device support. Reproduced on Asus P4540UQ:
(EE) NVIDIA: Failed to initialize the NVIDIA kernel module. Please see the
(EE) NVIDIA:     system's kernel log for additional error messages and
(EE) NVIDIA:     consult the NVIDIA README for details.
(EE) NVIDIA: Failed to initialize the NVIDIA kernel module. Please see the
(EE) NVIDIA:     system's kernel log for additional error messages and
(EE) NVIDIA:     consult the NVIDIA README for details.
(EE) [drm] Failed to open DRM device for (null): -22
(EE) [drm] Failed to open DRM device for pci:0000:01:00.0: -19
(EE) open /dev/dri/card1: Permission denied
(WW) Falling back to old probe method for modesetting
(II) modeset(1): using default …
> Full disable user display server again

- daemon/gdm-manager.c
The initial setup home dir should be owned by the initial user created
during the gnome-initial-setup to be able to copy all config to the new
user with the gnome-initial-setup-copy-worker.
The owner of this homedir is been changed if the session is different
from GDM_SESSION_DISPLAY_MODE_REUSE_VT but in this case the manager is
not calling this function.
This patch moves the call to this function outside the if-else to fix
the gnome-initial-setup process in the first case.
https://phabricator.endlessm.com/T26433
> manager: Chown initial-setup homedir on REUSE_VT

- data/Init.in
This reverts commit 9ec01da42ff2d7ea382b676ccbba0e3be8788460.
This approach does not work when user-display-server is enabled.
https://phabricator.endlessm.com/T26791
> Revert "Unset 'recordfail' grub variable on GDM start"

- debian/rules
This reverts commit 455f9d10654744731b86b92b68968cf0c0321c07.
Build with user-display-server support again.
https://phabricator.endlessm.com/T27501
> Revert "Full disable user display server again"

- debian/62-Endless-disable-wayland.rules
- debian/changelog
- debian/gdm3.install
This udev rule is no longer needed to disable wayland as we only enable one session and GDM automatically detects it as an X session based on the path it is installed (/usr/share/xsessions/endless.desktop).
GDM only consider a session to be a wayland session if the session's configuration file path ends with "/wayland-sessions". This check is done when loading the available sessions from the configured system dirs.
https://phabricator.endlessm.com/T30188
> Drop udev rule to disable wayland

- data/dconf/gdm.in
On Endless we ship the dconf profile under DATADIR/greeter-dconf-defaults and no profile under /var/lib/gdm3, so let's drop this debian change as it breaks for example showing the a11y menu which is configured to be displayed by default in the shipped dconf profile.
(looks like this change was added when importing debian/patches during the 3.37.9x/3.38 rebase).
https://phabricator.endlessm.com/T30874
> Properly load dconf profile

- debian/rules
In Autotools, the default runtime configuration path used to be
${GDM_RUN_DIR}/custom.conf, but in the Meson build system the fallback
changed to be the same as the custom.conf path in /etc (set to
/etc/gdm3/daemon.conf in Debian for historical reasons).
Explicitly set it to the path we used before switching to Meson, so
that configuration changes by gdm-disable-wayland are temporary as
intended, and do not persist to a subsequent boot.
[Cherry-picked from Debian commit ecb5e1e2f8]
> d/rules: Set runtime configuration path

- data/gdm.conf-custom.in
- data/gdm.schemas.in
We can't run on Wayland by default because the RPi4 does not support it
(it does not have a DRM driver yet), and we should avoid mixed
environments so we don't have to support both Xorg and Wayland on a
certain piece of hardware.
https://phabricator.endlessm.com/T30916
> data: Run the greeter session on X by default

- data/61-gdm.rules.in
- utils/gdm-runtime-config.c
- utils/meson.build
We can disable Wayland in runtime by invoking gdm-disable-wayland.
However, we may also want to enable Wayland in runtime for some
reasons. This idea is extended to modify more options/configurations in
runtime.
This commit renames gdm-disable-wayland to gdm-runtime-config and
unlocks the feature to modify more gdm configurations in runtime.
The new command format will be:
gdm-runtime-config set <group> <key> <value>
The configurable items refer to gdm.schemas. "<group>/<key>" combination
is the key in gdm.schemas.
For example, the original "gdm-disable-wayland" is replaced by
"gdm-runtime-config set daemon WaylandEnable false".
Link: https://gitlab.gnome.org/GNOME/gdm/-/merge_requests/115#note_944907
> utils: change gdm-disable-wayland to gdm-runtime-config

- debian/62-Endless-enable-wayland.rules
- debian/gdm3.install
Arm64 devices with supported DRM have better UI performance with
Wayland. EOS keeps Xorg by default for all platforms. So, this patch
only makes Wayland enabled on arm64 in runtime if the DRM is detected
(not simple frame buffer in used).
https://phabricator.endlessm.com/T30597
> Add udev rule to enable Wayland on arm64 if DRM presents

- debian/62-Endless-enable-wayland.rules
- debian/gdm3.install
This reverts commit 8d9402a83d560ed6ee56c2ff20a9d6e7794ed2b4.
We're making Wayland the default, on all platforms that Wayland is
used as default, making the reverted patch obsolete.
https://phabricator.endlessm.com/T31623
> Revert "Add udev rule to enable Wayland on arm64 if DRM presents"

- data/61-gdm.rules.in
We currently disable wayland on machines with the vendor nvidia driver upstream if hybrid graphics are in place because there is poor performance for multimonitor use cases.
But springing that change on users in F37 this late in the game isn't nice, so instead default to Xorg and provide wayland as an option in the menu.
https://bugzilla.redhat.com/show_bug.cgi?id=2128910
Have this patch from Fedora gdm.
Source: https://src.fedoraproject.org/rpms/gdm/c/27625e5ff87b21ad983d2bb53541361a7201755a
https://phabricator.endlessm.com/T35012
> udev: Allow wayland on hybrid vendor nvidia machines
